Alcoholic Additives
Alanii/NewHestia pull request #121
Opened 2020-10-23 16:34 UTC by Sylrene

Adds new mixed drinks and options to the alcohol dispensers.

2020-10-23 18:50 UTC, Looreydev requested changes

2020-10-23 18:50 UTC, Looreydev commented on code/modules/reagents/dispenser/dispenser_presets.dm
> +			/obj/item/weapon/reagent_containers/chem_disp_cartridge/mead,
This should not be here 2 times, the first is missing a comma too. Remove one of them and make sure the one that stays has a comma, else the list will break.

2020-10-24 00:01 UTC, Jackofashepard approved these changes

2020-10-24 11:04 UTC, EvenInDeathIStillServe requested changes
Just a couple grammar mistakes, and an unnecessary multiplication.

2020-10-24 11:04 UTC, EvenInDeathIStillServe commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	description = "A sweet, mint-flavored alcoholic beverage"
```suggestion
	description = "A sweet, mint-flavored alcoholic beverage."
```

2020-10-24 11:04 UTC, EvenInDeathIStillServe commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	if(prob(1*strength_mod))
```suggestion
	if(prob(strength_mod))
```
1*something = something

2020-10-24 11:04 UTC, EvenInDeathIStillServe commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	glass_desc = "Holding this glass will make you seem like high-soceity... if you were from the 1800s."
```suggestion
	glass_desc = "Holding this glass will make you seem like high-society... if you were from the 1800s."
```

2020-10-24 15:28 UTC, Looreydev requested changes
Fix the small stuff suggested above and it's a go from me. @Sylrene

2020-10-24 17:00 UTC, Mojamble commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	glass_desc = "Holding this glass will make you seem like high-soceity... if you were from the 1800s."
we live in a soceity

Also, I should have gone over this myself before handing it over to Sy. This is on me.

2020-10-25 14:54 UTC, Looreydev approved these changes
Looks okay now.

2020-10-25 14:55 UTC, merged