Miscellaneous fixes to items
Alanii/NewHestia pull request #279
Opened 2020-11-11 19:40 UTC by BurpleBineapple

Changes NTEF department berets in loadouts to "Fleet [department] beret" instead of "Surveyor Corps [department] beret"

Fixes the gas mask down sprite to be (hopefully) visible

2020-11-13 22:42 UTC, Looreydev requested changes

2020-11-13 22:42 UTC, Looreydev commented on maps/torch/loadout/loadout_head.dm
>  	berets["NTEF beret"] = /obj/item/clothing/head/beret/solgov/expedition
You left this one out.

```suggestion
	berets["NTEF beret"] = /obj/item/clothing/head/beret/solgov/fleet
```

2020-11-13 22:42 UTC, Looreydev commented on maps/torch/loadout/loadout_head.dm
>  	berets["NTEF beret"] = /obj/item/clothing/head/beret/solgov/expedition
@BurpleBineapple

2020-11-19 14:58 UTC, BurpleBineapple commented
Added the fix to it, sorry about that!

2020-11-22 15:48 UTC, Looreydev approved these changes

2020-11-22 15:48 UTC, merged