Small/big science update
Alanii/NewHestia pull request #367
Opened 2020-12-05 17:08 UTC by Guidesu

Purple asked me to do voting in the discord.
Casey#4535 in the discord suggested Senior Researcher be removed (nuked).
She got several positives feedback and suggested adding o-3 and o-4 to normal scientist which i did.

What i mostly modified was:
Removing SR from code.
Fixing Jobs having EC instead of the fleet. Because what i was told EC was nuked several months ago.
Adding O-1 , O-2 , O-3, O-4 to scientist. Or just adding O-3 + O-4.
Removing SMC Warrant Officer from roboticist and adding an fleet one.
Giving researcher assistant e-2 to e-6.
And adding two alt titles to compensate for the SR removal: Researcher Advisor and Senior Researcher.

If Loorey or Purple wishes to correct anything the code just do it! :)
Just don't let me wait for 3 days.
If you wish to discuss in discord just ping me.
Guidesu#7987

2020-12-05 17:34 UTC, gilvian commented
Science main here.

i will miss my EC stuff :(

Removing SMC from science seems okay

Dont give science assistant more ranks, they are supposed to be assistants, not have seniority ranks that corpsman can get, atleast max E4.

If we are removing senior role we dont need it as alt title, its fine with science having those 2 roles cut since nobody played them, or they tried to be big dick mcgees


Overall okay PR after those changes.

2020-12-05 17:40 UTC, Guidesu commented
Done!

2020-12-05 19:57 UTC, Looreydev requested changes

2020-12-05 19:57 UTC, Looreydev commented on maps/torch/job/research_jobs.dm
>  	title = "Scientist"
Delete the leading empty line here.

2020-12-05 19:57 UTC, Looreydev commented on maps/torch/job/research_jobs.dm
>  	)
Redundant Comma.

```suggestion
		"Chemical Researcher"
	)
```

2020-12-05 20:08 UTC, Guidesu commented on maps/torch/job/research_jobs.dm
>  	title = "Scientist"
deleted

2020-12-05 20:10 UTC, Guidesu commented
fixed

2020-12-08 08:44 UTC, Firefox13 commented on maps/torch/job/research_jobs.dm
> +		/datum/mil_rank/fleet/e6,
![изображение](https://user-images.githubusercontent.com/57810301/101460538-c7f4bb80-394a-11eb-80ff-f3b3f0304b2b.png)
this isn't e-4

2020-12-17 16:14 UTC, Looreydev commented
Closing this as we are not reviewing / accepting PR's on our old repo anymore.
New Repo: https://github.com/VestaOfOrion/Vesta.Bay/

2020-12-17 16:14 UTC, closed without merging