Turns out I semi-fucked prommies
Alanii/NewHestia pull request #369
Opened 2020-12-05 19:02 UTC by Yawet330

AAAAAAAAA SPEEDMERGE SO I DONT GET STABBED IN MY SLEEP

🆑 Yawet330
codetweak: Prommies are now Unathi with extra steps. Except they die harder. They take 3x braindamage when regenerating below 70 nutrition, and take 10 braindamage per tick when below 40. Lord help me
/🆑

2020-12-06 08:46 UTC, BurpleBineapple requested changes
I'm going to be picky for once, please axe the comments you've made with your changes. I can **see** what's changed; you don't need to comment it in the actual code.

2020-12-06 08:46 UTC, BurpleBineapple commented on code/game/objects/auras/regenerating_aura.dm
> +	nutrition_damage_mult = 3//Increased
```suggestion
	nutrition_damage_mult = 3
```

2020-12-06 08:46 UTC, BurpleBineapple commented on code/game/objects/auras/regenerating_aura.dm
> +		H.adjust_nutrition(10) //Increased hunger
```suggestion
		H.adjust_nutrition(10)
```

2020-12-06 08:46 UTC, BurpleBineapple commented on code/game/objects/auras/regenerating_aura.dm
> +	if(H.nutrition < 70 && innate_heal && (H.getBruteLoss() + H.getFireLoss() > 10)) //Increased
```suggestion
	if(H.nutrition < 70 && innate_heal && (H.getBruteLoss() + H.getFireLoss() > 10))
```

2020-12-06 08:46 UTC, BurpleBineapple commented on code/game/objects/auras/regenerating_aura.dm
> +				sponge.take_internal_damage(3)//Multiplied by three.
```suggestion
				sponge.take_internal_damage(3)
```

2020-12-06 08:46 UTC, BurpleBineapple commented on code/game/objects/auras/regenerating_aura.dm
> +	if(H.nutrition < 30 && innate_heal) //Increased
```suggestion
	if(H.nutrition < 30 && innate_heal)
```

2020-12-06 08:46 UTC, BurpleBineapple commented on code/game/objects/auras/regenerating_aura.dm
> +				sponge.take_internal_damage(10)//Put up
```suggestion
				sponge.take_internal_damage(10)
```

2020-12-06 15:22 UTC, Yawet330 commented
Sure; I was more commenting incase a downstream ETC wanted to revert it locally and couldn't find the PR

2020-12-06 15:24 UTC, Yawet330 commented
The adjustment of the ELSE statement was done because it would've set the original organ multiplier back down. Honk

2020-12-17 16:14 UTC, Looreydev commented
Closing this as we are not reviewing / accepting PR's on our old repo anymore.
New Repo: https://github.com/VestaOfOrion/Vesta.Bay/

2020-12-17 16:14 UTC, closed without merging